toran:
  build: .
  restart: always
  ports:
    - "8000:8000"
#   volumes:
#     - "./srv/toran:/toran-data"
#     - "./srv/toran/config.yml:/toran/app/toran/config.yml"
#     - "./srv/toran/cache:/toran/app/toran/cache"
